- name: Download Prometheus Node Exporter
  ansible.builtin.unarchive:
    src: "{{ exporter_url }}"
    dest: /opt
    remote_src: true

- name: Copy SystemD Exporter
  ansible.builtin.template:
    src: exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start Exporter Service
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    enabled: true